export const BUTTON_STYLE = {
  BRICK: 1,
  ROUNDED: 2,
};
export const BUTTON_TYPE = {
  PRIMARY: 1,
  SECONDARY: 2,
  ALERT_PRIMARY: 3,
  ALERT_SECONDARY: 4,
  TERTIARY: 5,
  TEXT_PRIMARY: 6,
  TEXT_DANGER: 7,
  SUCCESS_PRIMARY: 8,
  SUCCESS_SECONDARY: 9,
};
export const BUTTON_SIZE = {
  SMALL: 1,
  MEDIUM: 2,
  LARGE: 3,
  MEDIUM_LARGE: 4,
};
export const BUTTON_ALIGN = {
  INHERIT: 1,
};
export const COLOR = {
  PRIMARY: 1,
  SECONDARY: 2,
};
